import { Component } from '@angular/core';
import {AlertController, App, ModalController, NavController} from 'ionic-angular';
import {StorageService} from "../../../../services/storageService";
import {HttpService} from "../../../../services/httpService";
import {DatePipe} from "@angular/common";
import {DayReportEntryDetailAlertPage} from "../dayReportEntryDetailAlert/dayReportEntryDetailAlert";

@Component({
  selector: 'page-dayReportEntryDetail',
  templateUrl: 'dayReportEntryDetail.html'
})
export class DayReportEntryDetailPage {
  maxDate;
  itemName = '在班人员';
  isFocus = false;
  personText = '请选择';
  personData;
  personList = [
    {text:"甲"},
    {text:"乙"},
    {text:"丙"},
    {text:"丁"},
    {text:"戊"},
  ];
  dataesList=
    [
      {projectsName:"内部收入",projectsCode:"100",data:[]},
      {projectsName:"其他",projectsCode:"200",data:[]},
      {projectsName:"商流费用",projectsCode:"300",data:[]}
    ];
  dataesIndex=-1;
  dataIndex=-1;
  dtIndex=-1;
  weightedData = [
    101,102,103,104,105,106
  ];
  percentageData = 11;
  lossUnitPriceData = 22;
  data = 		[
    {
      "density": 2000001.1,
      "id": 10000019030112,
      "projectsName": "一、汽柴油销量",
      "projectsCode": "100010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "吨",
      "targetValue": 11,
      "count": 104,
      "price": null,
      "amount": 104,
      "difference": 93,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 1,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030113,
      "projectsName": "1、汽油92#",
      "projectsCode": "1000101",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": 10,
      "count": 50,
      "price": null,
      "amount": 50,
      "difference": 40,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 2,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030114,
      "projectsName": "2、汽油95#",
      "projectsCode": "1000102",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": 1,
      "count": 2,
      "price": null,
      "amount": 2,
      "difference": 1,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 3,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030115,
      "projectsName": "3、汽油98#",
      "projectsCode": "1000103",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 4,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030116,
      "projectsName": "4、柴油0#",
      "projectsCode": "1000104",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 5,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030117,
      "projectsName": "5、柴油-20#",
      "projectsCode": "1000105",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 6,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030118,
      "projectsName": "6、柴油-35#",
      "projectsCode": "1000106",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "升",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 7,
      "parentGroupCode": "100010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030119,
      "projectsName": "二、汽柴油销售收入",
      "projectsCode": "100020",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 8,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030120,
      "projectsName": "三、营销支出",
      "projectsCode": "100030",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 9,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030121,
      "projectsName": "1、价格直降",
      "projectsCode": "1000301",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 10,
      "parentGroupCode": "100030",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030122,
      "projectsName": "2、电子券",
      "projectsCode": "1000302",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 11,
      "parentGroupCode": "100030",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030123,
      "projectsName": "3、加油卡折扣",
      "projectsCode": "1000303",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 12,
      "parentGroupCode": "100030",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030124,
      "projectsName": "4、加油卡积分",
      "projectsCode": "1000304",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 13,
      "parentGroupCode": "100030",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030125,
      "projectsName": "5、油非互动",
      "projectsCode": "1000305",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 14,
      "parentGroupCode": "100030",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030126,
      "projectsName": "四、非油收入",
      "projectsCode": "100040",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 15,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030127,
      "projectsName": "五、非油毛利",
      "projectsCode": "100050",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 16,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030128,
      "projectsName": "六、内部收入合计",
      "projectsCode": "100060",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 17,
      "parentGroupCode": "100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030129,
      "projectsName": "一、发卡数量",
      "projectsCode": "200010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "张",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 18,
      "parentGroupCode": "200",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030130,
      "projectsName": "二、卡充值金额",
      "projectsCode": "200020",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 19,
      "parentGroupCode": "200",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030131,
      "projectsName": "三、非油库存",
      "projectsCode": "200030",
      "managementCode": "XZ20200522101147551TJ",
      "unit": null,
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 20,
      "parentGroupCode": "200",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030132,
      "projectsName": "一、员工成本",
      "projectsCode": "300010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 21,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030133,
      "projectsName": "1、工资",
      "projectsCode": "3000101",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 22,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030134,
      "projectsName": "2、工资附加",
      "projectsCode": "3000102",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 23,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030135,
      "projectsName": "3、保险及公积金",
      "projectsCode": "3000103",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 24,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030136,
      "projectsName": "4、劳务费",
      "projectsCode": "3000104",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 25,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030137,
      "projectsName": "5、升油奖励",
      "projectsCode": "3000105",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 26,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030138,
      "projectsName": "6、非油奖励",
      "projectsCode": "3000106",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 27,
      "parentGroupCode": "300010",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030139,
      "projectsName": "二、运输费",
      "projectsCode": "300020",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 28,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030140,
      "projectsName": "三、维修费",
      "projectsCode": "300030",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 29,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030141,
      "projectsName": "四、租赁费",
      "projectsCode": "300040",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 30,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030142,
      "projectsName": "五、水电暖费",
      "projectsCode": "300050",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 31,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030143,
      "projectsName": "1、水费",
      "projectsCode": "3000501",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 32,
      "parentGroupCode": "300050",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030144,
      "projectsName": "2、电费",
      "projectsCode": "3000502",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 33,
      "parentGroupCode": "300050",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030145,
      "projectsName": "3、取暖费",
      "projectsCode": "3000503",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 34,
      "parentGroupCode": "300050",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030146,
      "projectsName": "六、五项管理性费用",
      "projectsCode": "300060",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 35,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030147,
      "projectsName": "1、办公费",
      "projectsCode": "3000601",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 36,
      "parentGroupCode": "300060",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030148,
      "projectsName": "2、会议费",
      "projectsCode": "3000602",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 37,
      "parentGroupCode": "300060",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030149,
      "projectsName": "3、差旅费",
      "projectsCode": "3000603",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 38,
      "parentGroupCode": "300060",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030150,
      "projectsName": "4、业务招待费",
      "projectsCode": "3000604",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 39,
      "parentGroupCode": "300060",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030151,
      "projectsName": "5、出国人员经费",
      "projectsCode": "3000605",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 40,
      "parentGroupCode": "300060",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030152,
      "projectsName": "七、广告促销",
      "projectsCode": "300070",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 41,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030153,
      "projectsName": "八、合理损耗",
      "projectsCode": "300080",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 10,
      "count": 40,
      "price": 600,
      "amount": 24000,
      "difference": 23990,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 42,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030154,
      "projectsName": "1、汽油92#",
      "projectsCode": "3000801",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 10,
      "count": 20,
      "price": null,
      "amount": 20,
      "difference": 10,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 43,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030155,
      "projectsName": "2、汽油95#",
      "projectsCode": "3000802",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 44,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030156,
      "projectsName": "3、汽油98#",
      "projectsCode": "3000803",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 45,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030157,
      "projectsName": "4、柴油0#",
      "projectsCode": "3000804",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 46,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030158,
      "projectsName": "5、柴油-20#",
      "projectsCode": "3000805",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 47,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030159,
      "projectsName": "6、柴油-35#",
      "projectsCode": "3000806",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 48,
      "parentGroupCode": "300080",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030160,
      "projectsName": "九、咨询审计费",
      "projectsCode": "300090",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 49,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030161,
      "projectsName": "十、安全环保及行政收费",
      "projectsCode": "300100",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 50,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030162,
      "projectsName": "1、财产保险费",
      "projectsCode": "3001001",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 51,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030163,
      "projectsName": "2、排污费",
      "projectsCode": "3001002",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 52,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030164,
      "projectsName": "3、检测费",
      "projectsCode": "3001003",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 53,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030165,
      "projectsName": "4、警卫消防费",
      "projectsCode": "3001004",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 54,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030166,
      "projectsName": "5、安全生产费",
      "projectsCode": "3001005",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 55,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030167,
      "projectsName": "6、加油站道路开口费",
      "projectsCode": "3001006",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 56,
      "parentGroupCode": "300100",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030168,
      "projectsName": "十一、税费",
      "projectsCode": "300110",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 57,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030169,
      "projectsName": "十二、信息系统维护费",
      "projectsCode": "300120",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 58,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030170,
      "projectsName": "1、硬件设备维护费",
      "projectsCode": "3001201",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 59,
      "parentGroupCode": "300120",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030171,
      "projectsName": "2、专用网络租用费",
      "projectsCode": "3001202",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 60,
      "parentGroupCode": "300120",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030172,
      "projectsName": "3、软件维护及升级费",
      "projectsCode": "3001203",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 61,
      "parentGroupCode": "300120",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030173,
      "projectsName": "4、其他",
      "projectsCode": "3001204",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 62,
      "parentGroupCode": "300120",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030174,
      "projectsName": "十三、银行上门收款服务费",
      "projectsCode": "300130",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 63,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030175,
      "projectsName": "十四、自用产品及消耗",
      "projectsCode": "300140",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 64,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030176,
      "projectsName": "1、自用产品",
      "projectsCode": "3001401",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 65,
      "parentGroupCode": "300140",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030177,
      "projectsName": "2、物料消耗",
      "projectsCode": "3001402",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 66,
      "parentGroupCode": "300140",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030178,
      "projectsName": "3、低值易耗品",
      "projectsCode": "3001403",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 67,
      "parentGroupCode": "300140",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030179,
      "projectsName": "4、车辆用油",
      "projectsCode": "3001404",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 68,
      "parentGroupCode": "300140",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030180,
      "projectsName": "十五、公务性支出",
      "projectsCode": "300150",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 69,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030181,
      "projectsName": "十六、存货盘亏毁损和报废（减盘盈）",
      "projectsCode": "300160",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": 600,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 70,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030182,
      "projectsName": "十七、其他费用",
      "projectsCode": "300170",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 71,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030183,
      "projectsName": "1、劳动保护费",
      "projectsCode": "3001701",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 72,
      "parentGroupCode": "300170",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030184,
      "projectsName": "2、物业管理费用",
      "projectsCode": "3001702",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 73,
      "parentGroupCode": "300170",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030185,
      "projectsName": "3、图书资料费",
      "projectsCode": "3001703",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 74,
      "parentGroupCode": "300170",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030186,
      "projectsName": "4、绿化及环境卫生费",
      "projectsCode": "3001704",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 75,
      "parentGroupCode": "300170",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030187,
      "projectsName": "5、其他费用",
      "projectsCode": "3001705",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 76,
      "parentGroupCode": "300170",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030188,
      "projectsName": "十八、折旧折耗摊销",
      "projectsCode": "300180",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 77,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030189,
      "projectsName": "十九、财务费用",
      "projectsCode": "300190",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 0,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 78,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030190,
      "projectsName": "1、利息支出",
      "projectsCode": "3001901",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 79,
      "parentGroupCode": "300190",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030191,
      "projectsName": "2、利息收入",
      "projectsCode": "3001902",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 80,
      "parentGroupCode": "300190",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030192,
      "projectsName": "商流费合计",
      "projectsCode": "300200",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": 10,
      "count": 40,
      "price": null,
      "amount": 24000,
      "difference": 30,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 81,
      "parentGroupCode": "300",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030193,
      "projectsName": "营业外支出",
      "projectsCode": "400010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 82,
      "parentGroupCode": "400",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030194,
      "projectsName": "利润",
      "projectsCode": "500010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "元",
      "targetValue": -10,
      "count": -40,
      "price": null,
      "amount": -24000,
      "difference": -30,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 83,
      "parentGroupCode": "500",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    },
    {
      "density": 2000001.1,
      "id": 10000019030195,
      "projectsName": "在班人员",
      "projectsCode": "600010",
      "managementCode": "XZ20200522101147551TJ",
      "unit": "名字1,名字4,名字2",
      "targetValue": null,
      "count": 0,
      "price": null,
      "amount": 0,
      "difference": 0,
      "measures": null,
      "remark": null,
      "updateTime": null,
      "departCode": "13710",
      "departName": "中国石油天然气股份有限公司福建销售分公司",
      "sort": 84,
      "parentGroupCode": "600",
      "secontGroupCode": null,
      "isGroupTitle": null,
      "isGroupComputes": null,
      "createTime": "2020-05-20",
      "createUser": "系统管理员",
      "updateUser": null,
      "isUse": "1"
    }
  ];
  cellItem=[
    {itemName:"单位",itemValue:"unit"},
    {itemName:"目标值",itemValue:"targetValue"},
    {itemName:"发生数",itemValue:""},
    {itemName:"数量",itemValue:"count"},
    {itemName:"单价",itemValue:"price"},
    {itemName:"金额",itemValue:"amount"},
    {itemName:"差异",itemValue:"difference"},
    {itemName:"改进措施",itemValue:"measures"},
  ];
  constructor(public navCtrl: NavController,public httpService:HttpService,public storageService:StorageService,
              public alertCtrl:AlertController,public app:App,public datePipe:DatePipe,public modalCtrl:ModalController) {
    for(let i in this.data){
      if (this.data[i].targetValue==null){
        this.data[i].targetValue = 0;
      }
      if (this.data[i].parentGroupCode=="100"){
        this.data[i]["itemsList"] = [];
        this.dataesList[0].data.push(this.data[i])
      }else if(this.data[i].parentGroupCode=="200"){
        this.data[i]["itemsList"] = [];
        this.dataesList[1].data.push(this.data[i])
      }else if(this.data[i].parentGroupCode=="300"){
        this.data[i]["itemsList"] = [];
        this.dataesList[2].data.push(this.data[i])
      }else if(this.data[i].parentGroupCode=="400"){
        this.data[i]["data"] = [];
        this.dataesList.push(JSON.parse(JSON.stringify(this.data[i])))
      }else if(this.data[i].parentGroupCode=="500"){
        this.data[i]["data"] = [];
        this.dataesList.push(JSON.parse(JSON.stringify(this.data[i])))
      }
    }
    for (let j in this.dataesList){
      for (let i in this.dataesList[j].data){
        for (let x in this.data){
          if(this.dataesList[j].data[i].projectsCode == this.data[x].parentGroupCode){
            this.dataesList[j].data[i]["itemsList"].push(this.data[x])
          }
        }
      }
    }
  }
  ionViewDidEnter(){

  }
  showPerson(){
    let data1 = this.personList;
    let content = {
      item:{
        parent:[
          {itemValue:"text"},
        ],
      }
    }
    let body = {data:data1,content:content}
    let modal = this.modalCtrl.create(DayReportEntryDetailAlertPage,body);
    modal.present();
    modal.onDidDismiss(data=>{
      if(data&&data.selectedData){
        this.personText = "";
        this.personData = data.selectedData;
        for(let i in this.personData){
          this.personText += this.personData[i].text + ","
        }
        this.personText = this.personText.substring(0,this.personText.length-1);
      }
    })
  }
  hideFooter() {
    this.isFocus = true;
  }
  setNumForm(i,i2,i3,str,sort){
    this.isFocus = false;
    if (i>2){
      this.dataesList[i][str] = this.dataesList[i][str]*1;
      this.dataesList[i]["difference"] = this.dataesList[i]["amount"] - this.dataesList[i]["targetValue"]
    }else {
      if (i3==-1){
        this.dataesList[i].data[i2][str] = this.dataesList[i].data[i2][str]*1;
        if (sort<7){
          this.dataesList[i].data[i2].amount = this.dataesList[i].data[i2].count;
        }
        this.dataesList[i].data[i2].difference = this.dataesList[i].data[i2].amount - this.dataesList[i].data[i2].targetValue
      }else {
        this.dataesList[i].data[i2].itemsList[i3][str] = this.dataesList[i].data[i2].itemsList[i3][str]*1;
        if (sort<7){
          this.dataesList[i].data[i2]["itemsList"][i3].amount = this.dataesList[i].data[i2]["itemsList"][i3].count;
        }
        this.dataesList[i].data[i2]["itemsList"][i3].difference = this.dataesList[i].data[i2]["itemsList"][i3].amount - this.dataesList[i].data[i2]["itemsList"][i3].targetValue
      }
    }
  }
  showDataes(i){
    let content = document.getElementsByClassName("dataesContent");
    this.displayContent(content,i,"dataesIndex")
  }
  showData(i,i2){
    let index = i2;
    for (let j=0;j<i;j++){
      let len = this.dataesList[j].data.length;
      for (let x=0;x<len;x++){
        if (this.dataesList[j].data[x].itemsList.length>0){
          index += 1
        }
      }
    }
    for (let j=0;j<i2;j++){
      if (this.dataesList[i].data[j].itemsList.length==0){
        index -= 1;
      }
    }
    let content = document.getElementsByClassName("dataContent");
    this.displayContent(content,index,"dataIndex");
    let labelHeight = (<HTMLElement>document.getElementById("reportForm").getElementsByClassName("inputItem")[0]).offsetHeight;
    let dataTop = (<HTMLElement>document.getElementsByClassName("dataContent")[index]).offsetTop;
    (<HTMLElement>document.getElementById("reportForm").getElementsByClassName("scroll-content")[0]).scrollTop = dataTop - labelHeight;
  }
  showDt(i,i2,i3){
    let index = i3;
    if (i>2){
      console.log(i)
      for (let j=0;j<3;j++){
        let len = this.dataesList[j].data.length;
        for (let x=0;x<len;x++){
          index += this.dataesList[j].data[x].itemsList.length + 1;
        }
      }
      index += i-3;
    }else {
      for (let j=0;j<i;j++){
        let len = this.dataesList[j].data.length;
        for (let x=0;x<len;x++){
          index += this.dataesList[j].data[x].itemsList.length + 1;
        }
      }
    }
    for (let j=0;j<i2;j++){
      index += this.dataesList[i].data[j].itemsList.length + 1;
    }
    if (i3 == -1){
      index += this.dataesList[i].data[i2].itemsList.length + 1;
    }
    let content = document.getElementsByClassName("dtContent");
    this.displayContent(content,index,"dtIndex");
    let labelHeight = (<HTMLElement>document.getElementById("reportForm").getElementsByClassName("inputItem")[0]).offsetHeight;
    let dtTop = (<HTMLElement>document.getElementsByClassName("dtContent")[index]).offsetTop;
    (<HTMLElement>document.getElementById("reportForm").getElementsByClassName("scroll-content")[0]).scrollTop = dtTop - labelHeight;

  }
  displayContent(content,index,displayIndex){
    console.log(content)
    console.log(index)
    if (content.length>0){
      if ((<HTMLElement>content[index]).style.display=="block"){
        (<HTMLElement>content[index]).style.display="none";
      }else {
        if(this[displayIndex]>=0){
          (<HTMLElement>content[this[displayIndex]]).style.display="none";
        }
        (<HTMLElement>content[index]).style.display="block";
        this[displayIndex] = index;
      }
    }
    this.calcMethod();
  }
  calcMethod(){
    this.dataesList[0].data[0].count = 0;
    for (let i in this.dataesList[0].data[0]["itemsList"]){
      this.dataesList[0].data[0].count += this.dataesList[0].data[0]["itemsList"][i].amount*(this.weightedData[i]-1.1)/1000000;
    }
    this.dataesList[0].data[0].amount = this.dataesList[0].data[0].count;
    this.dataesList[0].data[0].difference = this.dataesList[0].data[0].amount - this.dataesList[0].data[0].targetValue;
    this.dataesList[0].data[2].amount = 0;
    this.dataesList[0].data[2].targetValue = 0;
    for (let i in this.dataesList[0].data[2]["itemsList"]){
      this.dataesList[0].data[2].amount += this.dataesList[0].data[2]["itemsList"][i].amount;
      this.dataesList[0].data[2].targetValue += this.dataesList[0].data[2]["itemsList"][i].targetValue;
    }
    this.dataesList[0].data[2].difference = this.dataesList[0].data[2].amount - this.dataesList[0].data[2].targetValue;
    this.dataesList[0].data[5].amount = this.dataesList[0].data[1].amount + this.dataesList[0].data[2].amount - this.dataesList[0].data[4].amount;
    this.dataesList[0].data[5].targetValue = this.dataesList[0].data[1].targetValue + this.dataesList[0].data[2].targetValue - this.dataesList[0].data[4].targetValue;
    this.dataesList[0].data[5].difference = this.dataesList[0].data[5].amount - this.dataesList[0].data[5].targetValue;
    this.dataesList[2].data[0].itemsList[5].amount = this.dataesList[0].data[4].amount*this.percentageData;
    this.dataesList[2].data[0].itemsList[5].targetValue = this.dataesList[0].data[4].targetValue*this.percentageData;
    this.dataesList[2].data[0].itemsList[5].difference = this.dataesList[2].data[0].itemsList[5].amount - this.dataesList[2].data[0].itemsList[5].targetValue;
    this.dataesList[2].data[4].amount = 0;
    this.dataesList[2].data[4].targetValue = 0;
    for (let i in this.dataesList[2].data[4]["itemsList"]){
      this.dataesList[2].data[4].amount += this.dataesList[2].data[4]["itemsList"][i].amount;
      this.dataesList[2].data[4].targetValue += this.dataesList[2].data[4]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[4].difference = this.dataesList[2].data[4].amount - this.dataesList[2].data[4].targetValue;
    this.dataesList[2].data[5].amount = 0;
    this.dataesList[2].data[5].targetValue = 0;
    for (let i in this.dataesList[2].data[5]["itemsList"]){
      this.dataesList[2].data[5].amount += this.dataesList[2].data[5]["itemsList"][i].amount;
      this.dataesList[2].data[5].targetValue += this.dataesList[2].data[5]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[5].difference = this.dataesList[2].data[5].amount - this.dataesList[2].data[5].targetValue;
    this.dataesList[2].data[7].price = this.lossUnitPriceData;
    this.dataesList[2].data[7].count = 0;
    this.dataesList[2].data[7].targetValue = 0;
    for (let i in this.dataesList[2].data[7]["itemsList"]){
      this.dataesList[2].data[7].count += this.dataesList[2].data[7]["itemsList"][i].amount*(this.weightedData[i]-1.1)/1000000;
      this.dataesList[2].data[7].targetValue += this.dataesList[2].data[7]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[7].amount = this.dataesList[2].data[7].count * this.dataesList[2].data[7].price;
    this.dataesList[2].data[7].difference = this.dataesList[2].data[7].amount - this.dataesList[2].data[7].targetValue;
    this.dataesList[2].data[9].amount = 0;
    this.dataesList[2].data[9].targetValue = 0;
    for (let i in this.dataesList[2].data[9]["itemsList"]){
      this.dataesList[2].data[9].amount += this.dataesList[2].data[9]["itemsList"][i].amount;
      this.dataesList[2].data[9].targetValue += this.dataesList[2].data[9]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[9].difference = this.dataesList[2].data[9].amount - this.dataesList[2].data[9].targetValue;
    this.dataesList[2].data[11].amount = 0;
    this.dataesList[2].data[11].targetValue = 0;
    for (let i in this.dataesList[2].data[11]["itemsList"]){
      this.dataesList[2].data[11].amount += this.dataesList[2].data[11]["itemsList"][i].amount;
      this.dataesList[2].data[11].targetValue += this.dataesList[2].data[11]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[11].difference = this.dataesList[2].data[11].amount - this.dataesList[2].data[11].targetValue;
    this.dataesList[2].data[13].amount = 0;
    this.dataesList[2].data[13].targetValue = 0;
    for (let i in this.dataesList[2].data[13]["itemsList"]){
      this.dataesList[2].data[13].amount += this.dataesList[2].data[13]["itemsList"][i].amount;
      this.dataesList[2].data[13].targetValue += this.dataesList[2].data[13]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[13].difference = this.dataesList[2].data[13].amount - this.dataesList[2].data[13].targetValue;
    this.dataesList[2].data[15].price = this.lossUnitPriceData;
    this.dataesList[2].data[15].amount = this.dataesList[2].data[15].count * this.dataesList[2].data[15].price/1000;
    this.dataesList[2].data[15].difference = this.dataesList[2].data[15].amount - this.dataesList[2].data[15].targetValue;
    this.dataesList[2].data[16].amount = 0;
    this.dataesList[2].data[16].targetValue = 0;
    for (let i in this.dataesList[2].data[16]["itemsList"]){
      this.dataesList[2].data[16].amount += this.dataesList[2].data[16]["itemsList"][i].amount;
      this.dataesList[2].data[16].targetValue += this.dataesList[2].data[16]["itemsList"][i].targetValue;
    }
    this.dataesList[2].data[16].difference = this.dataesList[2].data[16].amount - this.dataesList[2].data[16].targetValue;
    this.dataesList[2].data[18].amount = this.dataesList[2].data[18]["itemsList"][1].amount - this.dataesList[2].data[18]["itemsList"][0].amount;
    this.dataesList[2].data[18].targetValue = this.dataesList[2].data[18]["itemsList"][1].targetValue - this.dataesList[2].data[18]["itemsList"][0].targetValue;
    this.dataesList[2].data[18].difference = this.dataesList[2].data[18].amount - this.dataesList[2].data[18].targetValue;
    this.dataesList[2].data[19].amount = 0;
    this.dataesList[2].data[19].targetValue = 0;
    for (let i = 0;i < this.dataesList[2].data.length-1;i++){
      this.dataesList[2].data[19].amount += this.dataesList[2].data[i].amount;
      this.dataesList[2].data[19].targetValue += this.dataesList[2].data[i].targetValue;
    }
    this.dataesList[2].data[19].difference = this.dataesList[2].data[19].amount - this.dataesList[2].data[19].targetValue;
    this.dataesList[4]["amount"] = this.dataesList[0].data[5].amount - this.dataesList[2].data[19].amount - this.dataesList[3]["amount"];
    this.dataesList[4]["targetValue"] = this.dataesList[0].data[5].targetValue - this.dataesList[2].data[19].targetValue - this.dataesList[3]["targetValue"];
    this.dataesList[4]["difference"] = this.dataesList[4]["amount"] - this.dataesList[4]["targetValue"];
  }
  submitForm(){
    this.calcMethod();
    let alertCtrl = this.alertCtrl.create({
      title:"提交成功！"
    });
    alertCtrl.present();
    let data = [];
    for(let i in this.dataesList){
      for(let j in this.dataesList[i].data){
        data.push(this.dataesList[i].data[j]);
        for(let x in this.dataesList[i].data[j].itemsList){
          data.push(this.dataesList[i].data[j].itemsList[x])
        }
      }
    }
    console.log(data)
  }


}
